language: java
os: linux
dist: xenial
root: true

jdk:
  - oraclejdk8
  - oraclejdk11
  - oraclejdk14

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
    email:
      recipients:
        - fgsoftwarestudio@gmail.com
        - fgygh5804@gmail.com
        - 2009@epcarvalhais.org
      on_success: always
      on_failure: always